testapp/config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :questions
  resources :quizzes
  resources :posts
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

testapp/app/models/question.rb
class Question < ApplicationRecord
    belongs_to :quiz
    
    def test_method
        return "This is test method"
    end
    
    def self.test_class_method
      return "Hello, Worlds!"
    end
end

testapp/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:q_type, :content, :sug_ans, :explain, :seq_num, :quiz_id)
    end
    
end

testapp/app/helpers/questions_helper.rb
module QuestionsHelper
end

testapp/app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :q_type %>
    <%= form.text_field :q_type %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :sug_ans %>
    <%= form.text_field :sug_ans %>
  </div>

  <div class="field">
    <%= form.label :explain %>
    <%= form.text_area :explain %>
  </div>

  <div class="field">
    <%= form.label :seq_num %>
    <%= form.number_field :seq_num %>
  </div>

  <div class="field">
    <%= form.label :quiz_id %>
    <%= form.number_field :quiz_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

testapp/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

testapp/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Q type</th>
      <th>Content</th>
      <th>Sug ans</th>
      <th>Explain</th>
      <th>Seq num</th>
      <th>Quiz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %> 
      <tr>
        <td><%= question.q_type %></td>
        <td><%= question.content %></td>
        <td><%= question.sug_ans %></td>
        <td><%= question.explain %></td>
        <td><%= question.seq_num %></td>
        <td><%= question.quiz_id %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>


<br>

<%= link_to 'New Question', new_question_path %>

testapp/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

testapp/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Q type:</strong>
  <%= @question.q_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Sug ans:</strong>
  <%= @question.sug_ans %>
</p>

<p>
  <strong>Explain:</strong>
  <%= @question.explain %>
</p>

<p>
  <strong>Seq num:</strong>
  <%= @question.seq_num %>
</p>

<p>
  <strong>Quiz:</strong>
  <%= @question.quiz_id %>
</p>

<p>
  <%= @question.test_function %>
</p>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>